classes:
    FetcherPGSQLQueryBuilder:
        class: \Berthe\DAL\FetcherPGSQLQueryBuilder
        singleton: true
    DbReader:
        class: \Berthe\DAL\DbReader
        singleton: true
        arguments: [ @DbAdapter ]
    DbWriter:
        class: \Berthe\DAL\DbWriter
        singleton: true
        arguments: [ @DbAdapter ]
    DbAdapter:
        class: Zend_Db_Adapter_Abstract
        builder: \Zend_Db::factory
        arguments: [ %db.adapter, %db.params ]
    DbTranslator:
        class: \Evaneos\Berthe\DAL\Translator
        call:
            setDb: [ @DbWriter ]
    Memcached:
        class: \Memcached
        call:
            addServer: [ %memcached.host, %memcached.port ]
    FunctionalListException:
        class: \Berthe\ErrorHandler\FunctionalErrorListException
    # Translation block
    TranslationEngine:
        class: Translation_Manager
        builder: \EVFramework\Translation\InstanceCreator::factory
        singleton: true
        call:
            setEnableNotice: [ false ]
            registerStorage[0]: [ dbString, @TranslationStringDatabaseEngine ]
            setLogger: [ @I18nLogger ]
    TranslationStringDatabaseEngine:
        class: \EVFramework\Translation\StringDatabaseEngine
        singleton: true
        call:
            setDbAdapter: [ @DbWriter ]
    I18nLogger:
        class: \Monolog\Logger
        singleton: true
        arguments: [ 'i18n' ]
        call:
            pushHandler: [ @I18nFileLoggerHandler ]
            pushProcessor: [ @I18nWebProcessor ]
    I18nFileLoggerHandler:
        class: \Monolog\Handler\StreamHandler
        arguments: [ %log.i18n.file, %log.i18n.level ]
    I18nWebProcessor:
        class: \Monolog\Processor\WebProcessor